/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interGraf;

import Dominio.ItemVenda;
import Dominio.Venda;
import gerenTarefas.GerInterGraf;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;

/**
 *
 * @author pedro
 */
public class DlgConsultaVenda extends javax.swing.JDialog {

    private GerInterGraf gerIg;
    private Venda venSelecionado;
    
    public DlgConsultaVenda(java.awt.Frame parent, boolean modal, GerInterGraf gerIg) {
        super(parent, modal);
        this.gerIg = gerIg;
        venSelecionado = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        cmbTipo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoProdutos = new javax.swing.JButton();
        relatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar Compras do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        botaoBuscar.setBackground(new java.awt.Color(0, 153, 0));
        botaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/lupa.png"))); // NOI18N
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 0))); // NOI18N

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venda", "Cliente", "Data", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVendas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Venda", "Cliente", "Mês" }));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoExcluir.setBackground(new java.awt.Color(204, 0, 0));
        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/cancelar.png"))); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/novo-produto.png"))); // NOI18N
        botaoProdutos.setText("Produtos");
        botaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoProdutos)
                .addGap(46, 46, 46)
                .addComponent(botaoExcluir)
                .addGap(67, 67, 67)
                .addComponent(botaoCancelar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoProdutos))
                .addContainerGap())
        );

        relatorios.setBackground(new java.awt.Color(0, 153, 0));
        relatorios.setText("Relatórios");
        relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botaoBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relatorios)
                .addGap(18, 18, 18))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relatorios))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        
        try {
            List<Venda> lista = gerIg.getGerDominio().pesquisarVenda(cmbTipo.getSelectedIndex(), txtPesquisa.getText() ) ;
            
            // Limpar a tabela
            ((DefaultTableModel) tabelaVendas.getModel()).setRowCount(0);
            
            if ( lista.isEmpty() ) {
                JOptionPane.showMessageDialog(this, "Não existem registros com essa pesquisa.");
            } else {
                for ( Venda ven : lista ){
                    ((DefaultTableModel) tabelaVendas.getModel()).addRow( ven.toArray() );
                }
            }
            
        } catch ( NumberFormatException | ParseException ex) {
            //JOptionPane.showMessageDialog(this, "Favor informar um ID válido. Somente números.");            
            JOptionPane.showMessageDialog(this, ex);            
        } catch ( HibernateException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar pedido." + ex);
        } 
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        venSelecionado = null;
        this.setVisible(false);
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        venSelecionado = pegarLinhaSelecionada();
        if ( venSelecionado != null) {
            if ( JOptionPane.showConfirmDialog(this, "Deseja excluir a VENDA do cliente?" +
                    venSelecionado.getCliente().getNome(), "Confirmar", JOptionPane.YES_NO_OPTION  ) == JOptionPane.OK_OPTION  ) {
                try {
                    gerIg.getGerDominio().excluir(venSelecionado);
                    excluirLinhaSelecionada();
                    JOptionPane.showMessageDialog(this, "Venda excluída com sucesso.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "ERRO ao excluir CLIENTE.");
                    Logger.getLogger(DlgConsultaVenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 
        } 
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutosActionPerformed
        venSelecionado = pegarLinhaSelecionada();
        if ( venSelecionado != null ) {
            String msg = "";
            for (ItemVenda iv : venSelecionado.getItensVenda()  ) {
                String nome = iv.getChComposta().getProduto().getNome() + " -  " 
                            + iv.getChComposta().getProduto().getUnidade();
                msg = msg.concat(nome).concat("\n");
            }
            JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_botaoProdutosActionPerformed

    private void relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatoriosActionPerformed
        // GERAR COM O TIPO DE BUSCAR "CLIENTE"
        try {
            List<Venda> lista = gerIg.getGerDominio().pesquisarVenda(cmbTipo.getSelectedIndex(), txtPesquisa.getText() ) ;
            gerIg.getGerRelatorios().relComLista(lista, "relVendas.jasper");
        } catch ( HibernateException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar pedido." + ex);
        } 
    }//GEN-LAST:event_relatoriosActionPerformed
    
    public Venda getVendaSelecionado() {
        return venSelecionado;
    }
    
    private Venda pegarLinhaSelecionada() {
        venSelecionado = null;
        int linha = tabelaVendas.getSelectedRow();
        if (linha >= 0) {
            venSelecionado = (Venda) tabelaVendas.getValueAt(linha, 0);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um PEDIDO.");
        }  
        return venSelecionado;
    }
    
    private void excluirLinhaSelecionada() {
        int linha = tabelaVendas.getSelectedRow();
        if (linha >= 0) {
            ((DefaultTableModel) tabelaVendas.getModel()).removeRow(linha);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoProdutos;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JButton relatorios;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
