/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interGraf;

import gerenTarefas.GerInterGraf;

/**
 *
 * @author pedro
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private GerInterGraf gerIg;
    
    public FrmPrincipal(GerInterGraf newGerIg) {
        gerIg = newGerIg;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipalHome = new javax.swing.JPanel();
        labelImg = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        cadProduto = new javax.swing.JMenuItem();
        cadVenda = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        consultaCliente = new javax.swing.JMenuItem();
        consultaProdutos = new javax.swing.JMenuItem();
        consultaVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sítio Terra Alta");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        painelPrincipalHome.setBackground(new java.awt.Color(255, 255, 255));
        painelPrincipalHome.setAutoscrolls(true);

        labelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/cafe-do-brasil-logo-2.png"))); // NOI18N

        javax.swing.GroupLayout painelPrincipalHomeLayout = new javax.swing.GroupLayout(painelPrincipalHome);
        painelPrincipalHome.setLayout(painelPrincipalHomeLayout);
        painelPrincipalHomeLayout.setHorizontalGroup(
            painelPrincipalHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalHomeLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        painelPrincipalHomeLayout.setVerticalGroup(
            painelPrincipalHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalHomeLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));

        menuCadastros.setText("Cadastros");
        menuCadastros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosActionPerformed(evt);
            }
        });

        cadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/adicionar-usuario (1).png"))); // NOI18N
        cadCliente.setText("Cliente");
        cadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        menuCadastros.add(cadCliente);

        cadProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/novo-produto.png"))); // NOI18N
        cadProduto.setText("Produto");
        cadProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadProdutoActionPerformed(evt);
            }
        });
        menuCadastros.add(cadProduto);

        cadVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/adicionar-ao-carrinho.png"))); // NOI18N
        cadVenda.setText("Venda");
        cadVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVendaActionPerformed(evt);
            }
        });
        menuCadastros.add(cadVenda);

        barraMenu.add(menuCadastros);

        menuConsultas.setText("Consultas");
        menuConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        consultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/pesquisa-de-mercado.png"))); // NOI18N
        consultaCliente.setText("Clientes");
        consultaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaCliente);

        consultaProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/pesquisa.png"))); // NOI18N
        consultaProdutos.setText("Produtos");
        consultaProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaProdutosActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaProdutos);

        consultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interGraf/imagens/pesquisa.png"))); // NOI18N
        consultaVendas.setText("Vendas");
        consultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaVendasActionPerformed(evt);
            }
        });
        menuConsultas.add(consultaVendas);

        barraMenu.add(menuConsultas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipalHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadProdutoActionPerformed
        gerIg.abriJanelaCadProduto();
    }//GEN-LAST:event_cadProdutoActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        gerIg.abriJanelaCadCliente();
    }//GEN-LAST:event_cadClienteActionPerformed

    private void cadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVendaActionPerformed
        gerIg.abriJanelaCadVenda();
    }//GEN-LAST:event_cadVendaActionPerformed

    private void menuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrosActionPerformed

    private void consultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteActionPerformed
        gerIg.abriJanelaConsultaCliente();
    }//GEN-LAST:event_consultaClienteActionPerformed

    private void consultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaProdutosActionPerformed
        gerIg.abriJanelaConsultaProdutos();
    }//GEN-LAST:event_consultaProdutosActionPerformed

    private void consultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaVendasActionPerformed
        gerIg.abriJanelaConsultaVenda();
    }//GEN-LAST:event_consultaVendasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenuItem cadProduto;
    private javax.swing.JMenuItem cadVenda;
    private javax.swing.JMenuItem consultaCliente;
    private javax.swing.JMenuItem consultaProdutos;
    private javax.swing.JMenuItem consultaVendas;
    private javax.swing.JLabel labelImg;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JPanel painelPrincipalHome;
    // End of variables declaration//GEN-END:variables
}
